[workspace]
members = ["main", "business", "web"]

[workspace.package]
version = "0.8.2"
authors = ["Jan Veen <jan.veen@posteo.de>"]
description = "Tiny OIDC Provider"
homepage = "https://j.njsm.de/git/veenj/tiny-auth/src/branch/master/README.md"

license = "GPL-3.0-or-later"
edition = "2021"

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1

[workspace.dependencies]
clap = "2.33.3"
log = "0.4.11"
serde_derive = "1.0.115"
serde_yaml = "0.8.7"
serde_json = "1.0.57"
serde_urlencoded = "0.6.1"
chrono = "0.4.15"
regex = "1.3.9"
actix-rt = "2.8.0"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
actix-files = "0.6.2"
url = "2.1.1"
futures = "0.3"
tera = "1.5.0"
base64 = "0.12.3"
systemd = "0.5"
jsonwebtoken = "7.2.0"
rand = "0.7.3"
async-trait = "0.1.40"
rustls = { version = "0.20.8", features = ["dangerous_configuration"]}
rustls-pemfile = "1.0.2"
test-log = "0.2.12"
env_logger = "*"

[workspace.dependencies.openssl]
version = "0.10"
features = ["v110"]

[workspace.dependencies.ring]
version = "0.16.15"
features = ["alloc", "std"]

[workspace.dependencies.tokio]
version = "1.28.2"
features = ["full"]

[workspace.dependencies.actix-web]
version = "4.3.1"
features = ["rustls"]

[workspace.dependencies.uuid]
version = "0.8.1"
features = ["v4", "serde"]

[workspace.dependencies.serde]
version = "1.0.115"
features = ["derive"]

[workspace.dependencies.log4rs]
version = "0.13.0"
default-features = false
features = ["yaml_format", "file", "pattern_encoder", "json_encoder", "console_appender"]

[workspace.dependencies.vergen]
version = "8"
features = ["build", "git", "git2"]
