# tiny-auth: Tiny OIDC Provider
# Copyright (C) 2019 The tiny-auth developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
store:
  - configuration file:
      name: file store
      base: dev/config/store
  - ldap:
      name: LDAP
      bind dn format: cn={{ user }},ou=users,dc=example,dc=org
      urls:
        - ldap://localhost:1389
        - ldap://localhost:1390
      connect timeout: 5
      starttls: true

crypto:
  keys:
    - key: test/src/test/resources/keys/key.pem
      public key: test/src/test/resources/keys/public_key.pem
    - key: test/src/test/resources/keys/key_2.pem
      public key: test/src/test/resources/keys/public_key_2.pem
  pepper: x5ePiX0TmUF2HzuraKuab9exzumu2sO54bnlVhgCS5AAXxqyhSSuHbCiUmx0FxmjZH9Gb2obp0ff2imMS6z40Qcc

rate limit:
  events: 3
  period in seconds: 30

web:
  bind: localhost:34344
  public host:
    domain: localhost
    port: 34344
  static files: src/static
  cors:
    - http://correct.example
    - http://localhost:5173
    - http://localhost:34344
    - https://correct.example
    - https://localhost:5173
    - https://localhost:34344
  session timeout in seconds: 60000
  token timeout in seconds: 60
  refresh token timeout in seconds: 180
  secret key: 6nwYoK0L9J5ADFQE74CkkuLmTGMSd1skxHso9XwZNbsCbVmLIVH6L2aBIi2veuia3aQ3fnBzfwwlIuzCmWTEjAcc
#  tls:
#    key: test/src/test/resources/keys/tls-key.pem
#    certificate: test/src/test/resources/keys/tls-chain.pem
#    client ca: test/src/test/resources/keys/ca.pem
#    versions:
#      - 1.2
#      - 1.3

api:
  endpoint: localhost:8089