# tiny-auth: Tiny OIDC Provider
# Copyright (C) 2019 The tiny-auth developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
store:
  - configuration file:
      name: configuration file
      base: /etc/tiny-auth/store

rate limit:
  events: 3
  period in seconds: 300

crypto:
  keys:
    - key: /etc/tiny-auth/key.pem
      public key: /etc/tiny-auth/public-key.pem
  pepper: a random string used to secure passwords

web:
  bind: localhost:8088
  public host:
    domain: localhost
    port: 8088
  static files: /usr/share/tiny-auth/static
  cors:
    - http://localhost:8088
  session timeout in seconds: 300
  token timeout in seconds: 60
  refresh token timeout in seconds: 180
  session same site policy: lax
  secret key: set-a-random-string-of-at-least-64-characters-here

api:
  endpoint: localhost:8089
  public host:
    domain: localhost
    port: 8089

log:
  format: full
  fields:
    span events: false
    ansi: true
    file: true
    level: true
    line number: true
    target: false
    thread id: false
    thread name: false
    time: none
  filter:
    - warn
    - tiny_auth_main=info
    - tiny_auth_web=info
    - tiny_auth_business=info
    - tiny_auth_api=info
    - tiny_auth_ldap=info
    - tiny_auth=info

hot reload: true
